[package]
org = "wso2"
name = "backend"
version = "0.1.0"
distribution = "2201.3.1"

[build-options]
observabilityIncluded = true
# cloud="docker"

[[platform.java11.dependency]]
groupId = "TraversePack"
artifactId = "TraversePack"
version = "1.0-SNAPSHOT"

# transitive dependency of TraversePack:TraversePack:1.0-SNAPSHOT
[[platform.java11.dependency]]
groupId = "com.googlecode.json-simple"
artifactId = "json-simple"
version = "1.1.1"

# transitive dependency of com.googlecode.json-simple:json-simple:1.1.1
[[platform.java11.dependency]]
groupId = "junit"
artifactId = "junit"
version = "4.10"

# transitive dependency of com.googlecode.json-simple:json-simple:1.1.1
[[platform.java11.dependency]]
groupId = "org.hamcrest"
artifactId = "hamcrest-core"
version = "1.1"

# transitive dependency of TraversePack:TraversePack:1.0-SNAPSHOT
[[platform.java11.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.5"

# transitive dependency of TraversePack:TraversePack:1.0-SNAPSHOT
[[platform.java11.dependency]]
groupId = "org.hamcrest"
artifactId = "hamcrest-core"
version = "2.2"

# transitive dependency of org.hamcrest:hamcrest-core:2.2
[[platform.java11.dependency]]
groupId = "org.hamcrest"
artifactId = "hamcrest"
version = "2.2"

# transitive dependency of TraversePack:TraversePack:1.0-SNAPSHOT
[[platform.java11.dependency]]
groupId = "junit"
artifactId = "junit"
version = "4.13.2"

# transitive dependency of TraversePack:TraversePack:1.0-SNAPSHOT
[[platform.java11.dependency]]
groupId = "com.microsoft.azure"
artifactId = "azure-storage"
version = "8.6.6"

# transitive dependency of com.microsoft.azure:azure-storage:8.6.6
[[platform.java11.dependency]]
groupId = "com.fasterxml.jackson.core"
artifactId = "jackson-core"
version = "2.9.4"

# transitive dependency of com.microsoft.azure:azure-storage:8.6.6
[[platform.java11.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-api"
version = "1.7.12"

# transitive dependency of com.microsoft.azure:azure-storage:8.6.6
[[platform.java11.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-lang3"
version = "3.4"

# transitive dependency of com.microsoft.azure:azure-storage:8.6.6
[[platform.java11.dependency]]
groupId = "com.microsoft.azure"
artifactId = "azure-keyvault-core"
version = "1.2.4"

# transitive dependency of com.microsoft.azure:azure-storage:8.6.6
[[platform.java11.dependency]]
groupId = "com.google.guava"
artifactId = "guava"
version = "24.1.1-jre"

# transitive dependency of com.microsoft.azure:azure-storage:8.6.6
[[platform.java11.dependency]]
groupId = "com.google.code.findbugs"
artifactId = "jsr305"
version = "1.3.9"

# transitive dependency of com.microsoft.azure:azure-storage:8.6.6
[[platform.java11.dependency]]
groupId = "org.checkerframework"
artifactId = "checker-compat-qual"
version = "2.0.0"

# transitive dependency of com.microsoft.azure:azure-storage:8.6.6
[[platform.java11.dependency]]
groupId = "com.google.errorprone"
artifactId = "error_prone_annotations"
version = "2.1.3"

# transitive dependency of com.microsoft.azure:azure-storage:8.6.6
[[platform.java11.dependency]]
groupId = "com.google.j2objc"
artifactId = "j2objc-annotations"
version = "1.1"

# transitive dependency of com.microsoft.azure:azure-storage:8.6.6
[[platform.java11.dependency]]
groupId = "org.codehaus.mojo"
artifactId = "animal-sniffer-annotations"
version = "1.14"

# transitive dependency of TraversePack:TraversePack:1.0-SNAPSHOT
[[platform.java11.dependency]]
groupId = "org.apache.logging.log4j"
artifactId = "log4j-core"
version = "2.17.0"

# transitive dependency of org.apache.logging.log4j:log4j-core:2.17.0
[[platform.java11.dependency]]
groupId = "org.apache.logging.log4j"
artifactId = "log4j-api"
version = "2.17.0"

# transitive dependency of TraversePack:TraversePack:1.0-SNAPSHOT
[[platform.java11.dependency]]
groupId = "org.apache.logging.log4j"
artifactId = "log4j-jpl"
version = "2.17.0"

# transitive dependency of TraversePack:TraversePack:1.0-SNAPSHOT
[[platform.java11.dependency]]
groupId = "org.apache.logging.log4j"
artifactId = "log4j-api"
version = "2.14.1"

# transitive dependency of TraversePack:TraversePack:1.0-SNAPSHOT
[[platform.java11.dependency]]
groupId = "org.apache.logging.log4j"
artifactId = "log4j-core"
version = "2.14.1"
