openapi: 3.0.1
info:
  title: /
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9096"
paths:
  /LicenseManager/getLicense:
    get:
      operationId: getLicensemanagerGetlicense
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
  /LicenseManager/updateLicense:
    post:
      operationId: postLicensemanagerUpdatelicense
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [https://localhost:3000],\r\n\
            \        allowCredentials: true,\r\n        allowHeaders: [*],\r\n   \
            \     allowMethods: [GET,POST,PUT,OPTIONS,DELETE,PATCH,HEAD],\r\n    \
            \    exposeHeaders: [Access-Control-Allow-Origin]\r\n    }+json"
          : schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /LicenseManager/addLicense:
    post:
      operationId: postLicensemanagerAddlicense
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [https://localhost:3000],\r\n\
            \        allowCredentials: true,\r\n        allowHeaders: [*],\r\n   \
            \     allowMethods: [GET,POST,PUT,OPTIONS,DELETE,PATCH,HEAD],\r\n    \
            \    exposeHeaders: [Access-Control-Allow-Origin]\r\n    }+json"
          : schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /LicenseManager/checkLicense/{licName}/{licKey}:
    get:
      operationId: getLicensemanagerChecklicenseLicnameLickey
      parameters:
      - name: licName
        in: path
        required: true
        schema:
          type: string
      - name: licKey
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /LicenseManager/requestLicense:
    post:
      operationId: postLicensemanagerRequestlicense
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [https://localhost:3000],\r\n\
            \        allowCredentials: true,\r\n        allowHeaders: [*],\r\n   \
            \     allowMethods: [GET,POST,PUT,OPTIONS,DELETE,PATCH,HEAD],\r\n    \
            \    exposeHeaders: [Access-Control-Allow-Origin]\r\n    }+json"
          : schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /LicenseManager/approveLicense:
    post:
      operationId: postLicensemanagerApprovelicense
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [https://localhost:3000],\r\n\
            \        allowCredentials: true,\r\n        allowHeaders: [*],\r\n   \
            \     allowMethods: [GET,POST,PUT,OPTIONS,DELETE,PATCH,HEAD],\r\n    \
            \    exposeHeaders: [Access-Control-Allow-Origin]\r\n    }+json"
          : schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /LicenseManager/rejectLicense:
    post:
      operationId: postLicensemanagerRejectlicense
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [https://localhost:3000],\r\n\
            \        allowCredentials: true,\r\n        allowHeaders: [*],\r\n   \
            \     allowMethods: [GET,POST,PUT,OPTIONS,DELETE,PATCH,HEAD],\r\n    \
            \    exposeHeaders: [Access-Control-Allow-Origin]\r\n    }+json"
          : schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /LicenseManager/getLicenseRequests:
    get:
      operationId: getLicensemanagerGetlicenserequests
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
  /LicenseManager/getLibrary:
    get:
      operationId: getLicensemanagerGetlibrary
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
  /LicenseManager/getLibraries:
    get:
      operationId: getLicensemanagerGetlibraries
      parameters:
      - name: page
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: query
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
  /LicenseManager/updateLibrary:
    post:
      operationId: postLicensemanagerUpdatelibrary
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [https://localhost:3000],\r\n\
            \        allowCredentials: true,\r\n        allowHeaders: [*],\r\n   \
            \     allowMethods: [GET,POST,PUT,OPTIONS,DELETE,PATCH,HEAD],\r\n    \
            \    exposeHeaders: [Access-Control-Allow-Origin]\r\n    }+json"
          : schema: {}
      responses:
        "200":
          description: Ok
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: BadRequest
  /LicenseManager/addLibrary:
    post:
      operationId: postLicensemanagerAddlibrary
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [https://localhost:3000],\r\n\
            \        allowCredentials: true,\r\n        allowHeaders: [*],\r\n   \
            \     allowMethods: [GET,POST,PUT,OPTIONS,DELETE,PATCH,HEAD],\r\n    \
            \    exposeHeaders: [Access-Control-Allow-Origin]\r\n    }+json"
          : schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /LicenseManager/checkPack/{packName}:
    get:
      operationId: getLicensemanagerCheckpackPackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /LicenseManager/receiver:
    post:
      operationId: postLicensemanagerReceiver
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [https://localhost:3000],\r\n\
            \        allowCredentials: true,\r\n        allowHeaders: [*],\r\n   \
            \     allowMethods: [GET,POST,PUT,OPTIONS,DELETE,PATCH,HEAD],\r\n    \
            \    exposeHeaders: [Access-Control-Allow-Origin]\r\n    }+json"
          : schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /LicenseManager/getPackstatus:
    get:
      operationId: getLicensemanagerGetpackstatus
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /LicenseManager/getBlobData:
    get:
      operationId: getLicensemanagerGetblobdata
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /LicenseManager/processAllPacks:
    get:
      operationId: getLicensemanagerProcessallpacks
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /LicenseManager/deletePack/{packName}:
    post:
      operationId: postLicensemanagerDeletepackPackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /LicenseManager/getDownloadingText/{fileName}:
    get:
      operationId: getLicensemanagerGetdownloadingtextFilename
      parameters:
      - name: fileName
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          description: BadRequest
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
  /LicenseManager/getBlobFile/{fileName}:
    get:
      operationId: getLicensemanagerGetblobfileFilename
      parameters:
      - name: fileName
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          description: BadRequest
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
  /LicenseManager/gettempdata/{packName}:
    get:
      operationId: getLicensemanagerGettempdataPackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
  /LicenseManager/getallLibraryRequests:
    get:
      operationId: getLicensemanagerGetalllibraryrequests
      responses:
        "200":
          description: Ok
  /LicenseManager/addLibraryRequest/{packName}:
    post:
      operationId: postLicensemanagerAddlibraryrequestPackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [https://localhost:3000],\r\n\
            \        allowCredentials: true,\r\n        allowHeaders: [*],\r\n   \
            \     allowMethods: [GET,POST,PUT,OPTIONS,DELETE,PATCH,HEAD],\r\n    \
            \    exposeHeaders: [Access-Control-Allow-Origin]\r\n    }+json"
          : schema: {}
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
        "400":
          description: BadRequest
  /LicenseManager/addLibraryLicense/{packName}:
    post:
      operationId: postLicensemanagerAddlibrarylicensePackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          ? "application/{\r\n        allowOrigins: [https://localhost:3000],\r\n\
            \        allowCredentials: true,\r\n        allowHeaders: [*],\r\n   \
            \     allowMethods: [GET,POST,PUT,OPTIONS,DELETE,PATCH,HEAD],\r\n    \
            \    exposeHeaders: [Access-Control-Allow-Origin]\r\n    }+json"
          : schema: {}
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
  /LicenseManager/deleteData:
    get:
      operationId: getLicensemanagerDeletedata
      responses:
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components: {}
