openapi: 3.0.1
info:
  title: /
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9096"
paths:
  /getLicense:
    get:
      operationId: getGetlicense
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
  /updateLicense:
    post:
      operationId: postUpdatelicense
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /addLicense:
    post:
      operationId: postAddlicense
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /checkLicense/{licName}/{licKey}:
    get:
      operationId: getChecklicenseLicnameLickey
      parameters:
      - name: licName
        in: path
        required: true
        schema:
          type: string
      - name: licKey
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /requestLicense:
    post:
      operationId: postRequestlicense
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /approveLicense:
    post:
      operationId: postApprovelicense
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /rejectLicense:
    post:
      operationId: postRejectlicense
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /getLicenseRequests:
    get:
      operationId: getGetlicenserequests
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
  /getLibrary:
    get:
      operationId: getGetlibrary
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
  /getLibraries:
    get:
      operationId: getGetlibraries
      parameters:
      - name: page
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: query
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
  /updateLibrary:
    post:
      operationId: postUpdatelibrary
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: BadRequest
  /addLibrary:
    post:
      operationId: postAddlibrary
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /checkPackv0/{packName}:
    get:
      operationId: getCheckpackv0Packname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /receiverv0:
    post:
      operationId: postReceiverv0
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /getPackstatus:
    get:
      operationId: getGetpackstatus
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /getBlobData:
    get:
      operationId: getGetblobdata
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
  /processAllPacks:
    get:
      operationId: getProcessallpacks
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /deletePack/{packName}:
    post:
      operationId: postDeletepackPackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /getDownloadingText/{fileName}:
    get:
      operationId: getGetdownloadingtextFilename
      parameters:
      - name: fileName
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          description: BadRequest
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
  /getBlobFile/{fileName}:
    get:
      operationId: getGetblobfileFilename
      parameters:
      - name: fileName
        in: path
        required: true
        schema:
          type: string
      responses:
        "400":
          description: BadRequest
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
  /gettempdata/{packName}:
    get:
      operationId: getGettempdataPackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
  /getallLibraryRequests:
    get:
      operationId: getGetalllibraryrequests
      responses:
        "200":
          description: Ok
  /addLibraryRequest/{packName}:
    post:
      operationId: postAddlibraryrequestPackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
        "400":
          description: BadRequest
  /addLibraryLicense/{packName}:
    post:
      operationId: postAddlibrarylicensePackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: Ok
        "500":
          description: InternalServerError
  /deleteData:
    get:
      operationId: getDeletedata
      responses:
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /checkPack/{packName}:
    get:
      operationId: getCheckpackPackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
  /receiver/{packName}:
    post:
      operationId: postReceiverPackname
      parameters:
      - name: packName
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              description: Any type of entity body
      responses:
        "200":
          description: Ok
        "400":
          description: BadRequest
        "500":
          description: InternalServerError
components: {}
